In [1]:
import numpy as np

1. 기본 배열 생성: Python 리스트 [1, 2, 3, 4, 5]를 사용하여 Numpy 배열을 생성하고 출력하세요.

In [4]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

2. 배열의 평균 계산: 생성한 배열의 평균 값을 계산하세요.

In [5]:
x.mean()

3.0

3. arange 함수 사용: np.arange 함수를 사용하여 0부터 20까지의 숫자를 포함하는 배열을 생성하세요.

In [23]:
np.arange(0,21)
print(np.arange(21))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


4. 특정 간격의 배열 생성: np.linspace를 사용하여 0부터 1까지 10개의 숫자를 포함하는 배열을 생성하세요.

In [7]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

5. 다차원 배열 생성: np.array를 사용하여 임의의 값을 가진 5X6 모양의 2차원 배열을 생성하고, 차원을 확인하세요.

In [15]:
x = np.array([1,3,5,2,4,6,7,8,2,4,6,1,7,0,8,4,3,4,5,7,8,1,3,4,5,3,8,9,8,0])
x = x.reshape(5,6)
x.ndim

2

6. 배열의 형태 변경: 위에서 만든 2차원 배열을 reshape 메소드를 사용하여 3X10 배열의 형태로 변경하세요.

In [24]:
x.reshape(-1,10)

array([[1, 3, 5, 2, 4, 6, 7, 8, 2, 4],
       [6, 1, 7, 0, 8, 4, 3, 4, 5, 7],
       [8, 1, 3, 4, 5, 3, 8, 9, 8, 0]])

In [17]:
x = x.reshape(3,10)
x

array([[1, 3, 5, 2, 4, 6, 7, 8, 2, 4],
       [6, 1, 7, 0, 8, 4, 3, 4, 5, 7],
       [8, 1, 3, 4, 5, 3, 8, 9, 8, 0]])

7. 배열 슬라이싱: 생성한 2차원 배열에서 첫 번째 행을 추출하세요.

In [18]:
x[0]

array([1, 3, 5, 2, 4, 6, 7, 8, 2, 4])

8. 배열 인덱싱: 특정 위치의 값(예: 2행 3열)을 인덱싱하여 출력하세요.

In [27]:
print(x[1,2], x[1][2])

7 7


9. 배열의 덧셈: 임의의 값을 가진 두 개의 배열을 생성하고, 이들의 합을 계산하세요.

In [29]:
data1 = np.array([[1,2],[4,3]])
data2 = np.array([[9,5],[3,2]])

data1+data2

array([[10,  7],
       [ 7,  5]])

10. 배열의 곱셈: 두 배열의 요소별 곱셈을 수행하세요.

In [30]:
data1 = np.array([[1,2],[4,3]])
data2 = np.array([[9,5],[3,2]])

data1*data2

array([[ 9, 10],
       [12,  6]])